kind: Deployment
apiVersion: apps/v1
metadata:
  name: docker-demo
  namespace: sentinel
  labels:
    app: docker-demo
    app.kubernetes.io/component: docker-demo
    app.kubernetes.io/instance: docker-demo
    app.kubernetes.io/name: docker-demo
    app.kubernetes.io/part-of: docker-demo-app
    app.openshift.io/runtime-namespace: sentinel
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  minReadySeconds: 600 #https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds
  progressDeadlineSeconds: 21600 #https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#progress-deadline-seconds
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: docker-demo
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      imagePullSecrets: 
        - name: acr
      containers:
        - name: docker-demo
          image: edgeclustermgmt.azurecr.io/sentinel/docker-demo:latest
          envFrom:
          - configMapRef:
              name: configmap-file
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler