### Replaced
# kind: DeploymentConfig
# apiVersion: apps.openshift.io/v1
kind: Deployment
apiVersion: apps/v1
#
###
metadata:
  name: docker-demo
  namespace: sentinel
  labels:
    app: docker-demo
    app.kubernetes.io/component: docker-demo
    app.kubernetes.io/instance: docker-demo
    app.kubernetes.io/name: docker-demo
    app.kubernetes.io/part-of: docker-demo-app
    app.openshift.io/runtime-namespace: sentinel
spec:

  ### Replaced (https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment)
  # strategy:
  #   type: Rolling
  #   rollingParams:
  #     updatePeriodSeconds: 1
  #     intervalSeconds: 1
  #     timeoutSeconds: 600
  #     maxUnavailable: 25%
  #     maxSurge: 25%
  #   resources: {}
  #   activeDeadlineSeconds: 21600
  strategy:
    type: RollingUpdate
    rollingUpdate:
      ### Deleted
      # updatePeriodSeconds: 1
      # intervalSeconds: 1
      ### Deleted, replaced by .specs.minReadySeconds below  
      # timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    ### Deleted, replaced by .specs.progressDeadlineSeconds below  
    # activeDeadlineSeconds: 21600

  minReadySeconds: 600 #https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#min-ready-seconds
  progressDeadlineSeconds: 21600 #https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#progress-deadline-seconds
  #
  ###

  replicas: 1
  revisionHistoryLimit: 10
  ### Deleted
  # test: false

  ### Replaced
  # selector:
  #   app: docker-demo
  #   deploymentconfig: docker-demo
  selector:
    matchLabels:
      app: docker-demo
  #
  ###
  template:
    metadata:

      ### Deleted
      # creationTimestamp: null 

      labels:
        app: docker-demo
        ### Deleted
        # deploymentconfig: docker-demo

      ### Deleted
      # annotations:
      #   openshift.io/generated-by: OpenShiftWebConsole

    spec:
      imagePullSecrets: 
        - name: acr
      containers:
        - name: docker-demo
          image: edgeclustermgmt.azurecr.io/sentinel/docker-demo:latest
          envFrom:
          - configMapRef:
              name: configmap-file
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler