kind: Namespace
apiVersion: v1
metadata:
  name: sentinel
---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: docker-demo
  namespace: sentinel
  labels:
    app: docker-demo
    app.kubernetes.io/component: docker-demo
    app.kubernetes.io/instance: docker-demo
    app.kubernetes.io/name: docker-demo
    app.kubernetes.io/part-of: docker-demo-app
    app.openshift.io/runtime-namespace: sentinel
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: docker-demo
    deploymentconfig: docker-demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docker-demo
        deploymentconfig: docker-demo
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      imagePullSecrets: 
        - name: acr
      containers:
        - name: docker-demo
          image: edgeclustermgmt.azurecr.io/sentinel/docker-demo:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler